### PR TITLE
Major version bump: ran 2to3, changed buffer to memoryview, updated setup and tox config

### PR DESCRIPTION
**Pull request by kazeka**

### CODE REVIEW

**Comment by kazeka** [comment]
@bgreen-litl added what we talked about yesterday - turns out Travis CI likes the latest versions of the test-requirements

**Comment by bgreen-litl** [comment]
This looks good. My only question is can this be 1.1 rather than 2.0?  It doesn't break API and the databases seem to be interchangeable.

**Comment by kazeka** [comment]
@bgreen-litl good call - i added a fixup

**Comment by bgreen-litl** [comment]
:+1:

**Pull request merged**
